version: "3.8"

services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  bun:
    image: oven/bun:1
    volumes:
      - .:/app
    working_dir: /app
    command: bun run src/index.ts
    depends_on:
      - redis

volumes:
  redis-data:
